name: Deploy to Screencraft Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rsync
        run: |
          apt-get update
          apt-get install -y rsync
          rsync --version

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Test SSH connection
        run: ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo SSH connection successful"

      - name: Deploy via rsync over SSH
        run: |
          rsync -avz --delete --exclude '.git' --exclude '.github' \
            -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
