name: Deploy to Screencraft Server

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ubuntu:22.04 # Use a clean Ubuntu 22.04 container

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rsync and SSH
        run: |
          apt-get update || { echo "apt-get update failed"; exit 1; }
          apt-get install -y rsync openssh-client || { echo "apt-get install failed"; exit 1; }
          rsync --version || { echo "rsync not installed"; exit 1; }
          which rsync || { echo "rsync not found in PATH"; exit 1; }
          echo "rsync installed at: $(which rsync)"
        # Install rsync and openssh-client in the container

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Test SSH connection
        run: ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo SSH connection successful"

      - name: Deploy via rsync over SSH
        run: |
          rsync -avz --delete --exclude '.git' --exclude '.github' \
            -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }}" \
            ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}
